namespace DeltaMapper.SourceGen.AttributeSources
{
    internal static class IgnoreMemberAttributeSource
    {
        public const string AttributeName = "DeltaMapper.IgnoreMemberAttribute";
        public const string HintName = "IgnoreMemberAttribute.g.cs";
        public const string Source = """
            // <auto-generated />
            #nullable enable

            namespace DeltaMapper
            {
                [System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple = true)]
                public sealed class IgnoreMemberAttribute : System.Attribute
                {
                    public System.Type SourceType { get; }
                    public System.Type DestinationType { get; }
                    public string MemberName { get; }

                    public IgnoreMemberAttribute(System.Type sourceType, System.Type destinationType, string memberName)
                    {
                        SourceType = sourceType;
                        DestinationType = destinationType;
                        MemberName = memberName;
                    }
                }
            }
            """;
    }
}
