namespace DeltaMapper.SourceGen.AttributeSources
{
    internal static class MapMemberAttributeSource
    {
        public const string AttributeName = "DeltaMapper.MapMemberAttribute";
        public const string HintName = "MapMemberAttribute.g.cs";
        public const string Source = """
            // <auto-generated />
            #nullable enable

            namespace DeltaMapper
            {
                [System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple = true)]
                public sealed class MapMemberAttribute : System.Attribute
                {
                    public System.Type SourceType { get; }
                    public System.Type DestinationType { get; }
                    public string DestinationMember { get; }
                    public string SourceMember { get; }

                    public MapMemberAttribute(System.Type sourceType, System.Type destinationType, string destinationMember, string sourceMember)
                    {
                        SourceType = sourceType;
                        DestinationType = destinationType;
                        DestinationMember = destinationMember;
                        SourceMember = sourceMember;
                    }
                }
            }
            """;
    }
}
