namespace DeltaMapper.SourceGen.AttributeSources
{
    internal static class NullSubstituteAttributeSource
    {
        public const string AttributeName = "DeltaMapper.NullSubstituteAttribute";
        public const string HintName = "NullSubstituteAttribute.g.cs";
        public const string Source = """
            // <auto-generated />
            #nullable enable

            namespace DeltaMapper
            {
                [System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple = true)]
                public sealed class NullSubstituteAttribute : System.Attribute
                {
                    public System.Type SourceType { get; }
                    public System.Type DestinationType { get; }
                    public string MemberName { get; }
                    public object Value { get; }

                    public NullSubstituteAttribute(System.Type sourceType, System.Type destinationType, string memberName, object value)
                    {
                        SourceType = sourceType;
                        DestinationType = destinationType;
                        MemberName = memberName;
                        Value = value;
                    }
                }
            }
            """;
    }
}
