using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;

namespace DeltaMapper.SourceGen
{
    internal static class EmitHelper
    {
        // Attribute short names that mark a destination property as ignored
        private const string IgnoreAttributeShortName = "Ignore";
        private const string IgnoreAttributeAltName = "DeltaMapperIgnore";

        // ── map method emission ──────────────────────────────────────────────

        /// <summary>
        /// Emits the partial-class map method for one (src, dst) pair.
        /// knownPairs lets nested types and collection elements be mapped recursively.
        /// attrConfig supplies [IgnoreMember]/[NullSubstitute]/[MapMember] overrides.
        /// </summary>
        public static string EmitMapMethod(
            INamedTypeSymbol profileClass,
            INamedTypeSymbol src,
            INamedTypeSymbol dst,
            IReadOnlyList<(INamedTypeSymbol Src, INamedTypeSymbol Dst)>? knownPairs = null,
            AttributeConfig? attrConfig = null)
        {
            var ns = profileClass.ContainingNamespace.IsGlobalNamespace
                ? null
                : profileClass.ContainingNamespace.ToDisplayString();

            var srcFullName = src.ToDisplayString();
            var dstFullName = dst.ToDisplayString();
            var methodName = $"Map_{src.Name}_To_{dst.Name}";

            var pairs = knownPairs ?? Array.Empty<(INamedTypeSymbol, INamedTypeSymbol)>();
            var assignmentLines = BuildAssignmentLines(src, dst, pairs, attrConfig);

            var indent = ns is not null ? "    " : "";
            var nsOpen = ns is not null ? $"namespace {ns}\n{{\n" : "";
            var nsClose = ns is not null ? "\n}" : "";

            var accessibility = profileClass.DeclaredAccessibility.ToString().ToLowerInvariant();

            return $@"// <auto-generated />
#nullable enable
using System.Linq;
{nsOpen}{indent}{accessibility} partial class {profileClass.Name}
{indent}{{
{indent}    private static void {methodName}({srcFullName} src, {dstFullName} dst)
{indent}    {{
{indent}        {assignmentLines}
{indent}    }}
{indent}}}{nsClose}
";
        }

        /// <summary>
        /// Emits the partial-class factory method for one (src, dst) pair.
        /// The factory creates a new destination instance AND maps all properties in one call,
        /// enabling the fast path in Mapper.Map&lt;&gt;() to bypass the pipeline entirely.
        /// attrConfig supplies [IgnoreMember]/[NullSubstitute]/[MapMember] overrides.
        /// </summary>
        public static string EmitFactoryMethod(
            INamedTypeSymbol profileClass,
            INamedTypeSymbol src,
            INamedTypeSymbol dst,
            IReadOnlyList<(INamedTypeSymbol Src, INamedTypeSymbol Dst)>? knownPairs = null,
            AttributeConfig? attrConfig = null)
        {
            var ns = profileClass.ContainingNamespace.IsGlobalNamespace
                ? null
                : profileClass.ContainingNamespace.ToDisplayString();

            var srcFullName = src.ToDisplayString();
            var dstFullName = dst.ToDisplayString();
            var methodName = $"Create_{src.Name}_To_{dst.Name}";

            var pairs = knownPairs ?? Array.Empty<(INamedTypeSymbol, INamedTypeSymbol)>();

            var indent = ns is not null ? "    " : "";
            var nsOpen = ns is not null ? $"namespace {ns}\n{{\n" : "";
            var nsClose = ns is not null ? "\n}" : "";

            var accessibility = profileClass.DeclaredAccessibility.ToString().ToLowerInvariant();

            // Try object initializer for simple flat types (better JIT inlining)
            var publicName = $"Map{src.Name}To{dst.Name}";

            var initLines = TryBuildInitializerLines(src, dst, pairs, attrConfig);
            if (initLines is not null)
            {
                return $@"// <auto-generated />
#nullable enable
using System.Linq;
{nsOpen}{indent}{accessibility} partial class {profileClass.Name}
{indent}{{
{indent}    private static {dstFullName} {methodName}({srcFullName} src) => new()
{indent}    {{
{indent}        {initLines}
{indent}    }};

{indent}    /// <summary>
{indent}    /// Maps <see cref=""{srcFullName}""/> to <see cref=""{dstFullName}""/> with zero overhead.
{indent}    /// Call directly for maximum performance (bypasses IMapper pipeline).
{indent}    /// </summary>
{indent}    public static {dstFullName} {publicName}({srcFullName} src)
{indent}    {{
{indent}        System.ArgumentNullException.ThrowIfNull(src);
{indent}        return {methodName}(src);
{indent}    }}
{indent}}}{nsClose}
";
            }

            // Fallback: two-step pattern for complex types (nested/collection with control flow)
            var assignmentLines = BuildAssignmentLines(src, dst, pairs, attrConfig);
            return $@"// <auto-generated />
#nullable enable
using System.Linq;
{nsOpen}{indent}{accessibility} partial class {profileClass.Name}
{indent}{{
{indent}    private static {dstFullName} {methodName}({srcFullName} src)
{indent}    {{
{indent}        var dst = new {dstFullName}();
{indent}        {assignmentLines}
{indent}        return dst;
{indent}    }}

{indent}    /// <summary>
{indent}    /// Maps <see cref=""{srcFullName}""/> to <see cref=""{dstFullName}""/> with zero overhead.
{indent}    /// Call directly for maximum performance (bypasses IMapper pipeline).
{indent}    /// </summary>
{indent}    public static {dstFullName} {publicName}({srcFullName} src)
{indent}    {{
{indent}        System.ArgumentNullException.ThrowIfNull(src);
{indent}        return {methodName}(src);
{indent}    }}
{indent}}}{nsClose}
";
        }

        /// <summary>
        /// Tries to build object initializer lines (Prop = src.Prop,) for simple flat types.
        /// Returns null if any property requires control flow (nested, collection, etc.).
        /// attrConfig supplies [IgnoreMember]/[NullSubstitute]/[MapMember] overrides.
        /// </summary>
        private static string? TryBuildInitializerLines(
            INamedTypeSymbol src,
            INamedTypeSymbol dst,
            IReadOnlyList<(INamedTypeSymbol Src, INamedTypeSymbol Dst)> _,
            AttributeConfig? attrConfig = null)
        {
            var srcProps = GetReadablePropertiesWithSymbol(src);
            var dstProps = GetWritablePropertiesWithSymbol(dst);

            var lines = new List<string>();

            foreach (var dstProp in dstProps)
            {
                // Skip property-level [Ignore] attribute
                if (IsIgnored(dstProp)) continue;

                // [IgnoreMember] attribute config check
                if (attrConfig is not null && IsAttrIgnored(attrConfig, src, dst, dstProp.Name))
                    continue;

                // [MapMember] remapping: find if this dst property is remapped to a different src property
                var mapMember = attrConfig is not null
                    ? FindMapMember(attrConfig, src, dst, dstProp.Name)
                    : null;

                (string Name, ITypeSymbol Type, IPropertySymbol Symbol) srcProp;
                if (mapMember is not null)
                {
                    srcProp = srcProps.FirstOrDefault(s =>
                        string.Equals(s.Name, mapMember.SourceMember, StringComparison.OrdinalIgnoreCase));
                }
                else
                {
                    srcProp = srcProps.FirstOrDefault(s =>
                        string.Equals(s.Name, dstProp.Name, StringComparison.OrdinalIgnoreCase));
                }

                if (srcProp.Name is null) continue;

                // [NullSubstitute] attribute config check
                var nullSub = attrConfig is not null
                    ? FindNullSubstitute(attrConfig, src, dst, dstProp.Name)
                    : null;

                if (nullSub is not null)
                {
                    // NullSubstitute requires same-type; complex/collection falls back to two-step.
                    // Nullable<T> is permitted (valid ?? operand, same type, struct).
                    if (!SymbolEqualityComparer.Default.Equals(srcProp.Type, dstProp.Type))
                        return null;

                    bool isNullableVt = dstProp.Type is INamedTypeSymbol ntNv
                        && ntNv.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T;
                    if (!isNullableVt && dstProp.Type is INamedTypeSymbol complexNs && IsComplexType(complexNs))
                        return null;
                    if (dstProp.Type is INamedTypeSymbol namedNs && IsListType(namedNs))
                        return null;
                    if (dstProp.Type is IArrayTypeSymbol)
                        return null;

                    var defaultLiteral = FormatConstantLiteral(nullSub.Value);
                    lines.Add($"{dstProp.Name} = src.{srcProp.Name} ?? {defaultLiteral},");
                    continue;
                }

                // Only support simple same-type assignments for initializer
                if (!SymbolEqualityComparer.Default.Equals(srcProp.Type, dstProp.Type))
                    return null; // Not simple -- fall back to two-step

                if (dstProp.Type is INamedTypeSymbol complex && IsComplexType(complex))
                    return null; // Nested type -- needs control flow

                if (dstProp.Type is INamedTypeSymbol named && IsListType(named))
                    return null; // Collection -- needs control flow

                if (dstProp.Type is IArrayTypeSymbol)
                    return null; // Array -- needs control flow

                lines.Add($"{dstProp.Name} = src.{srcProp.Name},");
            }

            return lines.Count == 0
                ? null
                : string.Join("\n            ", lines);
        }


        /// <summary>Returns the hint name for the factory method file.</summary>
        public static string BuildFactoryFileName(INamedTypeSymbol profileClass, INamedTypeSymbol src, INamedTypeSymbol dst)
        {
            return $"{profileClass.Name}.{src.Name}_To_{dst.Name}.Factory.g.cs";
        }

        /// <summary>
        /// Emits a single file containing the [ModuleInitializer] method that registers
        /// all mappings from the given profile class with GeneratedMapRegistry.
        /// One file per profile class; one Register call per (src, dst) pair.
        /// </summary>
        public static string EmitModuleInitializer(
            INamedTypeSymbol profileClass,
            IReadOnlyList<(INamedTypeSymbol Src, INamedTypeSymbol Dst)> mappings)
        {
            var ns = profileClass.ContainingNamespace.IsGlobalNamespace
                ? null
                : profileClass.ContainingNamespace.ToDisplayString();

            var indent = ns is not null ? "    " : "";
            var nsOpen = ns is not null ? $"namespace {ns}\n{{\n" : "";
            var nsClose = ns is not null ? "\n}" : "";

            var sb = new StringBuilder();
            foreach (var (src, dst) in mappings)
            {
                var srcFull = src.ToDisplayString();
                var dstFull = dst.ToDisplayString();
                var mapMethod = $"Map_{src.Name}_To_{dst.Name}";
                var factoryMethod = $"Create_{src.Name}_To_{dst.Name}";
                sb.AppendLine(
                    $"{indent}        DeltaMapper.Runtime.GeneratedMapRegistry.Register<{srcFull}, {dstFull}>" +
                    $"(static (src, dst) => {mapMethod}(src, dst));");
                sb.AppendLine(
                    $"{indent}        DeltaMapper.Runtime.GeneratedMapRegistry.RegisterFactory<{srcFull}, {dstFull}>" +
                    $"(static src => {factoryMethod}(src));");
            }

            // Trim trailing newline added by AppendLine so the closing brace is on its own line
            var registerCalls = sb.ToString().TrimEnd('\r', '\n');

            var accessibility = profileClass.DeclaredAccessibility.ToString().ToLowerInvariant();

            return $@"// <auto-generated />
#nullable enable
{nsOpen}{indent}{accessibility} partial class {profileClass.Name}
{indent}{{
{indent}    [System.Runtime.CompilerServices.ModuleInitializer]
{indent}    internal static void RegisterGeneratedMaps_{profileClass.Name}()
{indent}    {{
{registerCalls}
{indent}    }}
{indent}}}{nsClose}
";
        }

        /// <summary>Returns the hint name for the ModuleInitializer file.</summary>
        public static string BuildModuleInitializerFileName(INamedTypeSymbol profileClass)
        {
            return $"{profileClass.Name}.ModuleInit.g.cs";
        }

        public static string BuildFileName(INamedTypeSymbol profileClass, INamedTypeSymbol src, INamedTypeSymbol dst)
        {
            return $"{profileClass.Name}.{src.Name}_To_{dst.Name}.g.cs";
        }

        // ── flat property matching (kept for backward-compat / legacy callers) ─

        public static List<(string SrcName, string DstName)> GetMatchingProperties(
            INamedTypeSymbol src, INamedTypeSymbol dst)
        {
            var srcProps = GetReadablePropertiesSimple(src);
            var dstProps = GetWritablePropertiesWithSymbol(dst)
                               .Where(p => !IsIgnored(p))
                               .ToList();

            var matches = new List<(string, string)>();
            foreach (var dstProp in dstProps)
            {
                var srcProp = srcProps.FirstOrDefault(s =>
                    string.Equals(s.Name, dstProp.Name, StringComparison.OrdinalIgnoreCase)
                    && SymbolEqualityComparer.Default.Equals(s.Type, dstProp.Type));

                if (srcProp.Name is not null)
                    matches.Add((srcProp.Name, dstProp.Name));
            }
            return matches;
        }

        // ── assignment building ──────────────────────────────────────────────

        private static string BuildAssignmentLines(
            INamedTypeSymbol src,
            INamedTypeSymbol dst,
            IReadOnlyList<(INamedTypeSymbol Src, INamedTypeSymbol Dst)> knownPairs,
            AttributeConfig? attrConfig = null)
        {
            var srcProps = GetReadablePropertiesWithSymbol(src);
            var dstProps = GetWritablePropertiesWithSymbol(dst);

            var lines = new List<string>();

            foreach (var dstProp in dstProps)
            {
                // Skip property-level [Ignore] attribute
                if (IsIgnored(dstProp))
                    continue;

                // [IgnoreMember] attribute config check
                if (attrConfig is not null && IsAttrIgnored(attrConfig, src, dst, dstProp.Name))
                    continue;

                // [MapMember] remapping: find if this dst property is remapped to a different src property
                var mapMember = attrConfig is not null
                    ? FindMapMember(attrConfig, src, dst, dstProp.Name)
                    : null;

                (string Name, ITypeSymbol Type, IPropertySymbol Symbol) srcProp;
                if (mapMember is not null)
                {
                    srcProp = srcProps.FirstOrDefault(s =>
                        string.Equals(s.Name, mapMember.SourceMember, StringComparison.OrdinalIgnoreCase));
                }
                else
                {
                    // Find matching source property by name (case-insensitive)
                    srcProp = srcProps.FirstOrDefault(s =>
                        string.Equals(s.Name, dstProp.Name, StringComparison.OrdinalIgnoreCase));
                }

                if (srcProp.Name is null)
                    continue;

                // [NullSubstitute] attribute config check
                var nullSub = attrConfig is not null
                    ? FindNullSubstitute(attrConfig, src, dst, dstProp.Name)
                    : null;

                if (nullSub is not null)
                {
                    // Emit dst.Prop = src.Prop ?? defaultValue; for same-type non-collection properties.
                    // Nullable<T> structs are permitted (same type, valid ?? operand).
                    // Block only for arrays, list types, and non-nullable complex classes/structs.
                    bool isNullableValueType = dstProp.Type is INamedTypeSymbol ntNullable
                        && ntNullable.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T;
                    bool isComplexNonNullable = !isNullableValueType
                        && dstProp.Type is INamedTypeSymbol ntComplex
                        && IsComplexType(ntComplex);

                    if (SymbolEqualityComparer.Default.Equals(srcProp.Type, dstProp.Type)
                        && !isComplexNonNullable
                        && !(dstProp.Type is INamedTypeSymbol ntList && IsListType(ntList))
                        && !(dstProp.Type is IArrayTypeSymbol))
                    {
                        var defaultLiteral = FormatConstantLiteral(nullSub.Value);
                        lines.Add($"dst.{dstProp.Name} = src.{srcProp.Name} ?? {defaultLiteral};");
                        continue;
                    }
                }

                var line = BuildPropertyAssignment(srcProp, dstProp, knownPairs);
                if (line is not null)
                    lines.Add(line);
            }

            return lines.Count == 0
                ? "// no matched properties"
                : string.Join("\n            ", lines);
        }

        private static string? BuildPropertyAssignment(
            (string Name, ITypeSymbol Type, IPropertySymbol Symbol) srcProp,
            (string Name, ITypeSymbol Type, IPropertySymbol Symbol) dstProp,
            IReadOnlyList<(INamedTypeSymbol Src, INamedTypeSymbol Dst)> knownPairs)
        {
            var dstType = dstProp.Type;
            var srcName = srcProp.Name;
            var dstName = dstProp.Name;

            // ── array type ───────────────────────────────────────────────────
            if (dstType is IArrayTypeSymbol dstArray)
            {
                ITypeSymbol? srcElement;
                if (srcProp.Type is IArrayTypeSymbol srcArr)
                    srcElement = srcArr.ElementType;
                else
                    srcElement = GetCollectionElementType(srcProp.Type as INamedTypeSymbol);

                if (srcElement is null)
                    return null;

                var dstElement = dstArray.ElementType;

                if (SymbolEqualityComparer.Default.Equals(srcElement, dstElement))
                {
                    // primitive/string elements -- direct .ToArray()
                    return $"dst.{dstName} = src.{srcName}?.ToArray();";
                }

                // complex element -- check if nested pair exists
                if (dstElement is INamedTypeSymbol dstElemNamedArr &&
                    srcElement is INamedTypeSymbol srcElemNamedArr &&
                    FindPair(knownPairs, srcElemNamedArr, dstElemNamedArr) is { } nestedPairArr)
                {
                    var nm = $"Map_{nestedPairArr.Src.Name}_To_{nestedPairArr.Dst.Name}";
                    var dstFull = nestedPairArr.Dst.ToDisplayString();
                    return $"dst.{dstName} = src.{srcName}?.Select(x => {{ if (x is null) return null!; var mapped = new {dstFull}(); {nm}(x, mapped); return mapped; }}).ToArray();";
                }

                return null;
            }

            // ── List<T> type ─────────────────────────────────────────────────
            if (dstType is INamedTypeSymbol dstListNamed && IsListType(dstListNamed))
            {
                var dstElement = dstListNamed.TypeArguments.Length == 1
                    ? dstListNamed.TypeArguments[0]
                    : null;
                if (dstElement is null) return null;

                ITypeSymbol? srcElement = GetCollectionElementType(srcProp.Type as INamedTypeSymbol);
                if (srcElement is null && srcProp.Type is IArrayTypeSymbol srcArrT)
                    srcElement = srcArrT.ElementType;

                if (srcElement is null) return null;

                if (SymbolEqualityComparer.Default.Equals(srcElement, dstElement))
                {
                    return $"dst.{dstName} = src.{srcName}?.ToList();";
                }

                if (dstElement is INamedTypeSymbol dstElemNamedList &&
                    srcElement is INamedTypeSymbol srcElemNamedList &&
                    FindPair(knownPairs, srcElemNamedList, dstElemNamedList) is { } nestedPairList)
                {
                    var nm = $"Map_{nestedPairList.Src.Name}_To_{nestedPairList.Dst.Name}";
                    var dstFull = nestedPairList.Dst.ToDisplayString();
                    return $"dst.{dstName} = src.{srcName}?.Select(x => {{ if (x is null) return null!; var mapped = new {dstFull}(); {nm}(x, mapped); return mapped; }}).ToList();";
                }

                return null;
            }

            // ── nested complex type ──────────────────────────────────────────
            if (dstType is INamedTypeSymbol dstComplex && IsComplexType(dstComplex))
            {
                if (srcProp.Type is INamedTypeSymbol srcComplex &&
                    FindPair(knownPairs, srcComplex, dstComplex) is { } nestedPair)
                {
                    var nm = $"Map_{nestedPair.Src.Name}_To_{nestedPair.Dst.Name}";
                    var dstFull = nestedPair.Dst.ToDisplayString();
                    return $"if (src.{srcName} is not null) {{ dst.{dstName} = new {dstFull}(); {nm}(src.{srcName}, dst.{dstName}); }}";
                }

                // No known pair -- skip
                return null;
            }

            // ── simple same-type assignment ──────────────────────────────────
            if (SymbolEqualityComparer.Default.Equals(srcProp.Type, dstType))
                return $"dst.{dstName} = src.{srcName};";

            return null; // type mismatch
        }

        // ── attribute config helpers ─────────────────────────────────────────

        /// <summary>
        /// Returns true if the named destination property should be skipped for the given (src, dst) pair
        /// due to an [IgnoreMember] attribute on the profile class.
        /// </summary>
        private static bool IsAttrIgnored(
            AttributeConfig config,
            INamedTypeSymbol src,
            INamedTypeSymbol dst,
            string memberName)
        {
            foreach (var ignore in config.Ignores)
            {
                if (SymbolEqualityComparer.Default.Equals(ignore.SourceType, src) &&
                    SymbolEqualityComparer.Default.Equals(ignore.DestinationType, dst) &&
                    string.Equals(ignore.MemberName, memberName, StringComparison.OrdinalIgnoreCase))
                {
                    return true;
                }
            }
            return false;
        }

        /// <summary>
        /// Returns the first matching <see cref="NullSubstituteConfig"/> for the given (src, dst, member) triple,
        /// or null if none is configured.
        /// </summary>
        private static NullSubstituteConfig? FindNullSubstitute(
            AttributeConfig config,
            INamedTypeSymbol src,
            INamedTypeSymbol dst,
            string memberName)
        {
            foreach (var ns in config.NullSubstitutes)
            {
                if (SymbolEqualityComparer.Default.Equals(ns.SourceType, src) &&
                    SymbolEqualityComparer.Default.Equals(ns.DestinationType, dst) &&
                    string.Equals(ns.MemberName, memberName, StringComparison.OrdinalIgnoreCase))
                {
                    return ns;
                }
            }
            return null;
        }

        /// <summary>
        /// Returns the first matching <see cref="MapMemberConfig"/> for the given (src, dst, destinationMember) triple,
        /// or null if none is configured.
        /// </summary>
        private static MapMemberConfig? FindMapMember(
            AttributeConfig config,
            INamedTypeSymbol src,
            INamedTypeSymbol dst,
            string destinationMember)
        {
            foreach (var mm in config.MapMembers)
            {
                if (SymbolEqualityComparer.Default.Equals(mm.SourceType, src) &&
                    SymbolEqualityComparer.Default.Equals(mm.DestinationType, dst) &&
                    string.Equals(mm.DestinationMember, destinationMember, StringComparison.OrdinalIgnoreCase))
                {
                    return mm;
                }
            }
            return null;
        }

        /// <summary>
        /// Formats a constant value as a valid C# literal for use in generated code.
        /// Strings get double quotes, chars get single quotes, null becomes "null".
        /// </summary>
        internal static string FormatConstantLiteral(object? value)
        {
            if (value is null)
                return "null";

            if (value is string s)
                return "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";

            if (value is char c)
                return "'" + (c == '\'' ? "\\'" : c == '\\' ? "\\\\" : c.ToString()) + "'";

            if (value is bool b)
                return b ? "true" : "false";

            if (value is float f)
                return f.ToString("R", CultureInfo.InvariantCulture) + "f";

            if (value is double d)
                return d.ToString("R", CultureInfo.InvariantCulture) + "d";

            if (value is decimal dec)
                return dec.ToString(CultureInfo.InvariantCulture) + "m";

            if (value is long l)
                return l.ToString() + "L";

            if (value is ulong ul)
                return ul.ToString() + "UL";

            if (value is uint ui)
                return ui.ToString() + "U";

            // int, byte, sbyte, short, ushort -- all emit as plain number
            return value.ToString() ?? "null";
        }

        // ── type-classification helpers ──────────────────────────────────────

        private static bool IsIgnored((string Name, ITypeSymbol Type, IPropertySymbol Symbol) prop)
        {
            return prop.Symbol.GetAttributes().Any(a =>
            {
                var name = a.AttributeClass?.Name ?? string.Empty;
                var fullName = a.AttributeClass?.ToDisplayString() ?? string.Empty;

                return name == IgnoreAttributeShortName ||
                       name == IgnoreAttributeAltName ||
                       name == IgnoreAttributeShortName + "Attribute" ||
                       name == IgnoreAttributeAltName + "Attribute" ||
                       fullName == "DeltaMapper.Ignore" ||
                       fullName == "DeltaMapper.DeltaMapperIgnore" ||
                       fullName == "DeltaMapper.IgnoreAttribute" ||
                       fullName == "DeltaMapper.DeltaMapperIgnoreAttribute";
            });
        }

        private static bool IsListType(INamedTypeSymbol type)
        {
            if (!type.IsGenericType) return false;
            var fullName = type.ConstructedFrom.ToDisplayString();
            return fullName == "System.Collections.Generic.List<T>" ||
                   fullName == "System.Collections.Generic.IList<T>" ||
                   fullName == "System.Collections.Generic.IEnumerable<T>" ||
                   fullName == "System.Collections.Generic.ICollection<T>" ||
                   fullName == "System.Collections.Generic.IReadOnlyList<T>";
        }

        private static bool IsComplexType(INamedTypeSymbol type)
        {
            if (type.SpecialType != SpecialType.None) return false; // primitives, string, etc.
            if (IsListType(type)) return false;
            if (type.TypeKind == TypeKind.Enum) return false;
            return type.TypeKind == TypeKind.Class || type.TypeKind == TypeKind.Struct;
        }

        private static ITypeSymbol? GetCollectionElementType(INamedTypeSymbol? type)
        {
            if (type is null || !type.IsGenericType) return null;
            return type.TypeArguments.Length == 1 ? type.TypeArguments[0] : null;
        }

        private static (INamedTypeSymbol Src, INamedTypeSymbol Dst)?
            FindPair(IReadOnlyList<(INamedTypeSymbol Src, INamedTypeSymbol Dst)> pairs,
                     INamedTypeSymbol src, INamedTypeSymbol dst)
        {
            foreach (var pair in pairs)
            {
                if (SymbolEqualityComparer.Default.Equals(pair.Src, src) &&
                    SymbolEqualityComparer.Default.Equals(pair.Dst, dst))
                    return pair;
            }
            return null;
        }

        // ── property readers ─────────────────────────────────────────────────

        private static List<(string Name, ITypeSymbol Type, IPropertySymbol Symbol)>
            GetReadablePropertiesWithSymbol(INamedTypeSymbol type)
        {
            return type.GetMembers()
                .OfType<IPropertySymbol>()
                .Where(p => !p.IsStatic && !p.IsIndexer && p.GetMethod is not null)
                .Select(p => (p.Name, (ITypeSymbol)p.Type, p))
                .ToList();
        }

        private static List<(string Name, ITypeSymbol Type, IPropertySymbol Symbol)>
            GetWritablePropertiesWithSymbol(INamedTypeSymbol type)
        {
            return type.GetMembers()
                .OfType<IPropertySymbol>()
                .Where(p => !p.IsStatic && !p.IsIndexer && p.SetMethod is not null && !p.SetMethod.IsInitOnly)
                .Select(p => (p.Name, (ITypeSymbol)p.Type, p))
                .ToList();
        }

        private static List<(string Name, ITypeSymbol Type)>
            GetReadablePropertiesSimple(INamedTypeSymbol type)
        {
            return type.GetMembers()
                .OfType<IPropertySymbol>()
                .Where(p => !p.IsStatic && !p.IsIndexer && p.GetMethod is not null)
                .Select(p => (p.Name, (ITypeSymbol)p.Type))
                .ToList();
        }
    }
}
