using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace DeltaMapper.SourceGen
{
    internal static class EmitHelper
    {
        // Attribute short names that mark a destination property as ignored
        private const string IgnoreAttributeShortName = "Ignore";
        private const string IgnoreAttributeAltName   = "DeltaMapperIgnore";

        // ── map method emission ──────────────────────────────────────────────

        /// <summary>
        /// Emits the partial-class map method for one (src, dst) pair.
        /// knownPairs lets nested types and collection elements be mapped recursively.
        /// </summary>
        public static string EmitMapMethod(
            INamedTypeSymbol profileClass,
            INamedTypeSymbol src,
            INamedTypeSymbol dst,
            IReadOnlyList<(INamedTypeSymbol Src, INamedTypeSymbol Dst)>? knownPairs = null)
        {
            var ns = profileClass.ContainingNamespace.IsGlobalNamespace
                ? null
                : profileClass.ContainingNamespace.ToDisplayString();

            var srcFullName = src.ToDisplayString();
            var dstFullName = dst.ToDisplayString();
            var methodName  = $"Map_{src.Name}_To_{dst.Name}";

            var pairs = knownPairs ?? Array.Empty<(INamedTypeSymbol, INamedTypeSymbol)>();
            var assignmentLines = BuildAssignmentLines(src, dst, pairs);

            var indent  = ns is not null ? "    " : "";
            var nsOpen  = ns is not null ? $"namespace {ns}\n{{\n" : "";
            var nsClose = ns is not null ? "\n}" : "";

            var accessibility = profileClass.DeclaredAccessibility.ToString().ToLowerInvariant();

            return $@"// <auto-generated />
#nullable enable
using System.Linq;
{nsOpen}{indent}{accessibility} partial class {profileClass.Name}
{indent}{{
{indent}    private static void {methodName}({srcFullName} src, {dstFullName} dst)
{indent}    {{
{indent}        {assignmentLines}
{indent}    }}
{indent}}}{nsClose}
";
        }

        /// <summary>
        /// Emits a single file containing the [ModuleInitializer] method that registers
        /// all mappings from the given profile class with GeneratedMapRegistry.
        /// One file per profile class; one Register call per (src, dst) pair.
        /// </summary>
        public static string EmitModuleInitializer(
            INamedTypeSymbol profileClass,
            IReadOnlyList<(INamedTypeSymbol Src, INamedTypeSymbol Dst)> mappings)
        {
            var ns = profileClass.ContainingNamespace.IsGlobalNamespace
                ? null
                : profileClass.ContainingNamespace.ToDisplayString();

            var indent  = ns is not null ? "    " : "";
            var nsOpen  = ns is not null ? $"namespace {ns}\n{{\n" : "";
            var nsClose = ns is not null ? "\n}" : "";

            var sb = new StringBuilder();
            foreach (var (src, dst) in mappings)
            {
                var srcFull   = src.ToDisplayString();
                var dstFull   = dst.ToDisplayString();
                var mapMethod = $"Map_{src.Name}_To_{dst.Name}";
                sb.AppendLine(
                    $"{indent}        DeltaMapper.Runtime.GeneratedMapRegistry.Register<{srcFull}, {dstFull}>" +
                    $"(static (src, dst) => {mapMethod}(src, dst));");
            }

            // Trim trailing newline added by AppendLine so the closing brace is on its own line
            var registerCalls = sb.ToString().TrimEnd('\r', '\n');

            var accessibility = profileClass.DeclaredAccessibility.ToString().ToLowerInvariant();

            return $@"// <auto-generated />
#nullable enable
{nsOpen}{indent}{accessibility} partial class {profileClass.Name}
{indent}{{
{indent}    [System.Runtime.CompilerServices.ModuleInitializer]
{indent}    internal static void RegisterGeneratedMaps_{profileClass.Name}()
{indent}    {{
{registerCalls}
{indent}    }}
{indent}}}{nsClose}
";
        }

        /// <summary>Returns the hint name for the ModuleInitializer file.</summary>
        public static string BuildModuleInitializerFileName(INamedTypeSymbol profileClass)
        {
            return $"{profileClass.Name}.ModuleInit.g.cs";
        }

        public static string BuildFileName(INamedTypeSymbol profileClass, INamedTypeSymbol src, INamedTypeSymbol dst)
        {
            return $"{profileClass.Name}.{src.Name}_To_{dst.Name}.g.cs";
        }

        // ── flat property matching (kept for backward-compat / legacy callers) ─

        public static List<(string SrcName, string DstName)> GetMatchingProperties(
            INamedTypeSymbol src, INamedTypeSymbol dst)
        {
            var srcProps = GetReadablePropertiesSimple(src);
            var dstProps = GetWritablePropertiesWithSymbol(dst)
                               .Where(p => !IsIgnored(p))
                               .ToList();

            var matches = new List<(string, string)>();
            foreach (var dstProp in dstProps)
            {
                var srcProp = srcProps.FirstOrDefault(s =>
                    string.Equals(s.Name, dstProp.Name, StringComparison.OrdinalIgnoreCase)
                    && SymbolEqualityComparer.Default.Equals(s.Type, dstProp.Type));

                if (srcProp.Name is not null)
                    matches.Add((srcProp.Name, dstProp.Name));
            }
            return matches;
        }

        // ── assignment building ──────────────────────────────────────────────

        private static string BuildAssignmentLines(
            INamedTypeSymbol src,
            INamedTypeSymbol dst,
            IReadOnlyList<(INamedTypeSymbol Src, INamedTypeSymbol Dst)> knownPairs)
        {
            var srcProps = GetReadablePropertiesWithSymbol(src);
            var dstProps = GetWritablePropertiesWithSymbol(dst);

            var lines = new List<string>();

            foreach (var dstProp in dstProps)
            {
                // Skip [Ignore] properties
                if (IsIgnored(dstProp))
                    continue;

                // Find matching source property by name (case-insensitive)
                var srcProp = srcProps.FirstOrDefault(s =>
                    string.Equals(s.Name, dstProp.Name, StringComparison.OrdinalIgnoreCase));

                if (srcProp.Name is null)
                    continue;

                var line = BuildPropertyAssignment(srcProp, dstProp, knownPairs);
                if (line is not null)
                    lines.Add(line);
            }

            return lines.Count == 0
                ? "// no matched properties"
                : string.Join("\n            ", lines);
        }

        private static string? BuildPropertyAssignment(
            (string Name, ITypeSymbol Type, IPropertySymbol Symbol) srcProp,
            (string Name, ITypeSymbol Type, IPropertySymbol Symbol) dstProp,
            IReadOnlyList<(INamedTypeSymbol Src, INamedTypeSymbol Dst)> knownPairs)
        {
            var dstType = dstProp.Type;
            var srcName = srcProp.Name;
            var dstName = dstProp.Name;

            // ── array type ───────────────────────────────────────────────────
            if (dstType is IArrayTypeSymbol dstArray)
            {
                ITypeSymbol? srcElement;
                if (srcProp.Type is IArrayTypeSymbol srcArr)
                    srcElement = srcArr.ElementType;
                else
                    srcElement = GetCollectionElementType(srcProp.Type as INamedTypeSymbol);

                if (srcElement is null)
                    return null;

                var dstElement = dstArray.ElementType;

                if (SymbolEqualityComparer.Default.Equals(srcElement, dstElement))
                {
                    // primitive/string elements — direct .ToArray()
                    return $"dst.{dstName} = src.{srcName}?.ToArray();";
                }

                // complex element — check if nested pair exists
                if (dstElement is INamedTypeSymbol dstElemNamedArr &&
                    srcElement is INamedTypeSymbol srcElemNamedArr &&
                    FindPair(knownPairs, srcElemNamedArr, dstElemNamedArr) is { } nestedPairArr)
                {
                    var nm      = $"Map_{nestedPairArr.Src.Name}_To_{nestedPairArr.Dst.Name}";
                    var dstFull = nestedPairArr.Dst.ToDisplayString();
                    return $"dst.{dstName} = src.{srcName}?.Select(x => {{ if (x is null) return null!; var mapped = new {dstFull}(); {nm}(x, mapped); return mapped; }}).ToArray();";
                }

                return null;
            }

            // ── List<T> type ─────────────────────────────────────────────────
            if (dstType is INamedTypeSymbol dstListNamed && IsListType(dstListNamed))
            {
                var dstElement = dstListNamed.TypeArguments.Length == 1
                    ? dstListNamed.TypeArguments[0]
                    : null;
                if (dstElement is null) return null;

                ITypeSymbol? srcElement = GetCollectionElementType(srcProp.Type as INamedTypeSymbol);
                if (srcElement is null && srcProp.Type is IArrayTypeSymbol srcArrT)
                    srcElement = srcArrT.ElementType;

                if (srcElement is null) return null;

                if (SymbolEqualityComparer.Default.Equals(srcElement, dstElement))
                {
                    return $"dst.{dstName} = src.{srcName}?.ToList();";
                }

                if (dstElement is INamedTypeSymbol dstElemNamedList &&
                    srcElement is INamedTypeSymbol srcElemNamedList &&
                    FindPair(knownPairs, srcElemNamedList, dstElemNamedList) is { } nestedPairList)
                {
                    var nm      = $"Map_{nestedPairList.Src.Name}_To_{nestedPairList.Dst.Name}";
                    var dstFull = nestedPairList.Dst.ToDisplayString();
                    return $"dst.{dstName} = src.{srcName}?.Select(x => {{ if (x is null) return null!; var mapped = new {dstFull}(); {nm}(x, mapped); return mapped; }}).ToList();";
                }

                return null;
            }

            // ── nested complex type ──────────────────────────────────────────
            if (dstType is INamedTypeSymbol dstComplex && IsComplexType(dstComplex))
            {
                if (srcProp.Type is INamedTypeSymbol srcComplex &&
                    FindPair(knownPairs, srcComplex, dstComplex) is { } nestedPair)
                {
                    var nm      = $"Map_{nestedPair.Src.Name}_To_{nestedPair.Dst.Name}";
                    var dstFull = nestedPair.Dst.ToDisplayString();
                    return $"if (src.{srcName} is not null) {{ dst.{dstName} = new {dstFull}(); {nm}(src.{srcName}, dst.{dstName}); }}";
                }

                // No known pair — skip
                return null;
            }

            // ── simple same-type assignment ──────────────────────────────────
            if (SymbolEqualityComparer.Default.Equals(srcProp.Type, dstType))
                return $"dst.{dstName} = src.{srcName};";

            return null; // type mismatch
        }

        // ── type-classification helpers ──────────────────────────────────────

        private static bool IsIgnored((string Name, ITypeSymbol Type, IPropertySymbol Symbol) prop)
        {
            return prop.Symbol.GetAttributes().Any(a =>
            {
                var name     = a.AttributeClass?.Name ?? string.Empty;
                var fullName = a.AttributeClass?.ToDisplayString() ?? string.Empty;

                return name     == IgnoreAttributeShortName           ||
                       name     == IgnoreAttributeAltName             ||
                       name     == IgnoreAttributeShortName + "Attribute" ||
                       name     == IgnoreAttributeAltName   + "Attribute" ||
                       fullName == "DeltaMapper.Ignore"               ||
                       fullName == "DeltaMapper.DeltaMapperIgnore"    ||
                       fullName == "DeltaMapper.IgnoreAttribute"      ||
                       fullName == "DeltaMapper.DeltaMapperIgnoreAttribute";
            });
        }

        private static bool IsListType(INamedTypeSymbol type)
        {
            if (!type.IsGenericType) return false;
            var fullName = type.ConstructedFrom.ToDisplayString();
            return fullName == "System.Collections.Generic.List<T>" ||
                   fullName == "System.Collections.Generic.IList<T>" ||
                   fullName == "System.Collections.Generic.IEnumerable<T>" ||
                   fullName == "System.Collections.Generic.ICollection<T>" ||
                   fullName == "System.Collections.Generic.IReadOnlyList<T>";
        }

        private static bool IsComplexType(INamedTypeSymbol type)
        {
            if (type.SpecialType != SpecialType.None) return false; // primitives, string, etc.
            if (IsListType(type)) return false;
            if (type.TypeKind == TypeKind.Enum) return false;
            return type.TypeKind == TypeKind.Class || type.TypeKind == TypeKind.Struct;
        }

        private static ITypeSymbol? GetCollectionElementType(INamedTypeSymbol? type)
        {
            if (type is null || !type.IsGenericType) return null;
            return type.TypeArguments.Length == 1 ? type.TypeArguments[0] : null;
        }

        private static (INamedTypeSymbol Src, INamedTypeSymbol Dst)?
            FindPair(IReadOnlyList<(INamedTypeSymbol Src, INamedTypeSymbol Dst)> pairs,
                     INamedTypeSymbol src, INamedTypeSymbol dst)
        {
            foreach (var pair in pairs)
            {
                if (SymbolEqualityComparer.Default.Equals(pair.Src, src) &&
                    SymbolEqualityComparer.Default.Equals(pair.Dst, dst))
                    return pair;
            }
            return null;
        }

        // ── property readers ─────────────────────────────────────────────────

        private static List<(string Name, ITypeSymbol Type, IPropertySymbol Symbol)>
            GetReadablePropertiesWithSymbol(INamedTypeSymbol type)
        {
            return type.GetMembers()
                .OfType<IPropertySymbol>()
                .Where(p => !p.IsStatic && !p.IsIndexer && p.GetMethod is not null)
                .Select(p => (p.Name, (ITypeSymbol)p.Type, p))
                .ToList();
        }

        private static List<(string Name, ITypeSymbol Type, IPropertySymbol Symbol)>
            GetWritablePropertiesWithSymbol(INamedTypeSymbol type)
        {
            return type.GetMembers()
                .OfType<IPropertySymbol>()
                .Where(p => !p.IsStatic && !p.IsIndexer && p.SetMethod is not null && !p.SetMethod.IsInitOnly)
                .Select(p => (p.Name, (ITypeSymbol)p.Type, p))
                .ToList();
        }

        private static List<(string Name, ITypeSymbol Type)>
            GetReadablePropertiesSimple(INamedTypeSymbol type)
        {
            return type.GetMembers()
                .OfType<IPropertySymbol>()
                .Where(p => !p.IsStatic && !p.IsIndexer && p.GetMethod is not null)
                .Select(p => (p.Name, (ITypeSymbol)p.Type))
                .ToList();
        }
    }
}
