using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.CodeAnalysis;

namespace DeltaMapper.SourceGen
{
    internal static class EmitHelper
    {
        public static string EmitMapMethod(INamedTypeSymbol profileClass, INamedTypeSymbol src, INamedTypeSymbol dst)
        {
            var ns = profileClass.ContainingNamespace.IsGlobalNamespace
                ? null
                : profileClass.ContainingNamespace.ToDisplayString();

            var srcFullName = src.ToDisplayString();
            var dstFullName = dst.ToDisplayString();
            var methodName = $"Map_{src.Name}_To_{dst.Name}";

            // Match destination writable properties to source readable properties by name
            var assignments = GetMatchingProperties(src, dst);

            var assignmentLines = string.Join("\n            ",
                assignments.Select(p => $"dst.{p.DstName} = src.{p.SrcName};"));

            var indent = ns is not null ? "    " : "";
            var nsOpen = ns is not null ? $"namespace {ns}\n{{\n" : "";
            var nsClose = ns is not null ? "\n}" : "";

            return $@"// <auto-generated />
#nullable enable
{nsOpen}{indent}public partial class {profileClass.Name}
{indent}{{
{indent}    private static void {methodName}({srcFullName} src, {dstFullName} dst)
{indent}    {{
{indent}        {assignmentLines}
{indent}    }}
{indent}}}{nsClose}
";
        }

        public static List<(string SrcName, string DstName)> GetMatchingProperties(
            INamedTypeSymbol src, INamedTypeSymbol dst)
        {
            var srcProps = GetReadableProperties(src);
            var dstProps = GetWritableProperties(dst);

            var matches = new List<(string, string)>();
            foreach (var dstProp in dstProps)
            {
                var srcProp = srcProps.FirstOrDefault(s =>
                    string.Equals(s.Name, dstProp.Name, StringComparison.OrdinalIgnoreCase)
                    && SymbolEqualityComparer.Default.Equals(s.Type, dstProp.Type));

                if (srcProp.Name is not null)
                    matches.Add((srcProp.Name, dstProp.Name));
            }
            return matches;
        }

        public static string BuildFileName(INamedTypeSymbol profileClass, INamedTypeSymbol src, INamedTypeSymbol dst)
        {
            return $"{profileClass.Name}.{src.Name}_To_{dst.Name}.g.cs";
        }

        private static List<(string Name, ITypeSymbol Type)> GetReadableProperties(INamedTypeSymbol type)
        {
            return type.GetMembers()
                .OfType<IPropertySymbol>()
                .Where(p => !p.IsStatic && !p.IsIndexer && p.GetMethod is not null)
                .Select(p => (p.Name, (ITypeSymbol)p.Type))
                .ToList();
        }

        private static List<(string Name, ITypeSymbol Type)> GetWritableProperties(INamedTypeSymbol type)
        {
            return type.GetMembers()
                .OfType<IPropertySymbol>()
                .Where(p => !p.IsStatic && !p.IsIndexer && p.SetMethod is not null)
                .Select(p => (p.Name, (ITypeSymbol)p.Type))
                .ToList();
        }
    }
}
