namespace DeltaMapper.SourceGen
{
    internal static class GenerateMapAttributeSource
    {
        public const string AttributeName = "DeltaMapper.GenerateMapAttribute";
        public const string HintName = "GenerateMapAttribute.g.cs";
        public const string Source = """
            // <auto-generated />
            #nullable enable

            namespace DeltaMapper
            {
                [System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple = true)]
                public sealed class GenerateMapAttribute : System.Attribute
                {
                    public System.Type Source { get; }
                    public System.Type Destination { get; }

                    public GenerateMapAttribute(System.Type source, System.Type destination)
                    {
                        Source = source;
                        Destination = destination;
                    }
                }
            }
            """;
    }
}
